{% set name = "oslo.concurrency" %}
{% set version = "4.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 306f637680b48228e3eadea48a21008726e0a76069966f696de94b7c23741b4b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: True  # [py<35]

requirements:
  host:
    - pbr !=2.1.0,>=2.0.0
    - pip
    - python
  run:
    - pbr !=2.1.0,>=2.0.0
    - oslo.config >=5.2.0
    - oslo.i18n >=3.15.3
    - oslo.utils >=3.33.0
    - six >=1.10.0
    - fasteners >=0.7.0
    - enum34 >=1.0.4  # [py2k]
    - pip
    - python

test:
  imports:
    - oslo_concurrency
    - oslo_concurrency.fixture.lockutils
    - oslo_concurrency.lockutils
    - oslo_concurrency.opts
    - oslo_concurrency.processutils
    - oslo_concurrency.version
    - oslo_concurrency.watchdog

about:
  home: https://github.com/openstack/oslo.concurrency
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: The oslo.concurrency library has utilities for safely running multi-thread, multi-process applications using locking mechanisms and for running external processes

extra:
  recipe-maintainers:
    - pg-hbk
    - sy-hbk
